--- 
pid: tmp/pids/thin.pid
log: log/thin.log
max_conns: 1024
timeout: 30
port: 8004
max_persistent_conns: 512
chdir: /var/www/vhosts/colaruby.com/rails
environment: production
address: 127.0.0.1
servers: 1
daemonize: true
